version: '3.7'

services: 
    web:
        build: .
        volumes: 
            - static_volume:/app/static
        expose: 
            - 8000
        env_file: 
            - ./.env
    nginx:
        build: ./nginx
        volumes: 
            - static_volume:/app/static
        ports: 
            - 80:80
        depends_on: 
            - web

volumes: 
    static_volume: